version: '3.8'

services:
  postgres_server:
    image: bitnami/postgresql
    container_name: convites_leticia
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=convites_leticia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5501:5432'
    networks:
      - public_network

networks:
  public_network:
    driver: bridge

volumes:
  postgres_data:
